### ISSUE TITLE
Wrong order for version

### ISSUE THREAD

**Issue by DIG-** [xmake-io/xrepo-docs#1]
### Xmake Version

2.8.5

### Operating System Version and Architecture

Windows 11 22H2

### Describe Bug

The documentation sort versions as strings [#build.lua@254](https://github.com/xmake-io/xrepo-docs/blob/master/build.lua#L254), this generates a wrong order in documentation like for Python:
```
2.7.18, 3.10.11, 3.10.6, 3.11.3, 3.7.9, 3.8.10, 3.9.10, 3.9.13, 3.9.5, 3.9.6
              ^-------^                        [              ]-->--------->|
       [                        ]-->---------------------------------------->|
```

### Expected Behavior

Use semantic versioning for version order in documentation:
```2.7.18, 3.7.9, 3.8.10, 3.9.5, 3.9.6, 3.9.10, 3.9.13, 3.10.6, 3.10.11, 3.11.3```

### Project Configuration

N/A

### Additional Information and Error Logs

N/A

**Comment by waruqi** [comment]
https://github.com/xmake-io/xrepo-docs/commit/51864d6a7e9594d33d128b41452e35ca62ce4453
